# Global Framework Settings
# Supported Browsers: chrome, edge
browser=chrome

# Application URLs
url=https://www.coverfox.com/
base.url=https://www.coverfox.com/
car.insurance.url=https://www.coverfox.com/car-insurance/?hp=1

# Timeouts in Seconds
timeout=20
implicit.wait=10
explicit.wait=10

# Screenshot output directory
screenshot.dir=screenshots
