# Global Framework Settings
# Supported Browsers: chrome, edge
browser=chrome

<<<<<<< HEAD
# Application URLs
url=https://www.coverfox.com/
base.url=https://www.coverfox.com/
car.insurance.url=https://www.coverfox.com/car-insurance/?hp=1

# Timeouts in Seconds
timeout=20
implicit.wait=10
explicit.wait=10

# Screenshot output directory
screenshot.dir=screenshots
=======
# Application URL
url=https://www.coverfox.com/

# Timeouts in Seconds
timeout=10
excelFilePath=./src/test/resources/testdata/DataDrivenTest.xlsx
excelWritePath=C:\Users\2478754\eclipse-workspace\com.hackathon.project\excel_test_output\TestCasesStatus.xlsx
>>>>>>> master
