# Global Framework Settings
# Supported Browsers: chrome, edge
browser=chrome

# Application URL
url=https://www.coverfox.com/

# Timeouts in Seconds
timeout=10
excelFilePath=./src/test/resources/testdata/DataDrivenTest.xlsx
excelWritePath=C:\Users\2478754\eclipse-workspace\com.hackathon.project\excel_test_output\TestCasesStatus.xlsx